"""Catalogo de fuentes de noticias (Peru + Ecuador) con URLs y RSS feeds.

Estructura: lista de dicts con campos:
  categoria, pais, nombre, url, rss_url, tipo, notas

Tipos:
  - rss:    tiene feed RSS estandar (mas comun en medios y WP)
  - html:   solo HTML, requiere scraping con selectores
  - twitter: cuenta X/Twitter, requiere API o scraping (no auto)
  - manual: marcado en el catalogo pero sin scraping automatico

Para agregar/corregir URLs:
  python -m noticias.cli set-rss --pais PE --nombre "Gestion" --rss "https://..."
"""

# ============================================================
# PERU
# ============================================================
FUENTES_PE: list[dict] = [
    # --- COYUNTURA POLITICA: medios principales ---
    {"categoria": "Coyuntura Politica", "pais": "PE", "nombre": "El Comercio",
     "url": "https://elcomercio.pe/politica/",
     "rss_url": "https://elcomercio.pe/feed/", "tipo": "rss"},
    {"categoria": "Coyuntura Politica", "pais": "PE", "nombre": "Gestion",
     "url": "https://gestion.pe/politica/",
     "rss_url": "https://gestion.pe/arcio/rss/category/politica/", "tipo": "rss"},
    {"categoria": "Coyuntura Politica", "pais": "PE", "nombre": "La Republica",
     "url": "https://larepublica.pe/politica",
     "rss_url": "https://larepublica.pe/feed/", "tipo": "rss"},
    {"categoria": "Coyuntura Politica", "pais": "PE", "nombre": "Peru 21",
     "url": "https://peru21.pe/politica/",
     "rss_url": "https://peru21.pe/arcio/rss/category/politica/", "tipo": "rss"},
    {"categoria": "Coyuntura Politica", "pais": "PE", "nombre": "RPP",
     "url": "https://rpp.pe/politica",
     "rss_url": "https://rpp.pe/politica.xml", "tipo": "rss"},

    # --- INSTITUCION: Congreso, ministerios, agencias ---
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "Congreso - Proyectos de Ley",
     "url": "https://wb2server.congreso.gob.pe/spley-portal/",
     "tipo": "html",
     "notas": "Cubierto por modulo scraper/ (API formal)"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "El Peruano",
     "url": "https://elperuano.pe/", "tipo": "html",
     "notas": "Diario oficial; revisar /noticias/ y /normaslegales/"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "Canal Congreso",
     "url": "https://canalncongreso.gob.pe/", "tipo": "html"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "Agenda del Congreso",
     "url": "https://comunicaciones.congreso.gob.pe/agenda/",
     "rss_url": "https://comunicaciones.congreso.gob.pe/agenda/feed/",
     "tipo": "rss",
     "notas": "Cubierto por modulo mesas_tecnicas/"},
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "Presidencia del Consejo de Ministros",
     "url": "https://www.gob.pe/pcm",
     "rss_url": "https://www.gob.pe/pcm/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "Ministerio de Relaciones Exteriores",
     "url": "https://www.gob.pe/rree",
     "rss_url": "https://www.gob.pe/rree/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "Ministerio de Economia y Finanzas",
     "url": "https://www.gob.pe/mef",
     "rss_url": "https://www.gob.pe/mef/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "Ministerio de Educacion",
     "url": "https://www.gob.pe/minedu",
     "rss_url": "https://www.gob.pe/minedu/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "Ministerio de Comercio Exterior y Turismo",
     "url": "https://www.gob.pe/mincetur",
     "rss_url": "https://www.gob.pe/mincetur/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "Ministerio de Transportes y Comunicaciones",
     "url": "https://www.gob.pe/mtc",
     "rss_url": "https://www.gob.pe/mtc/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "Presidencia",
     "url": "https://www.gob.pe/presidencia",
     "rss_url": "https://www.gob.pe/presidencia/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "OSIPTEL",
     "url": "https://www.osiptel.gob.pe/",
     "rss_url": "https://www.gob.pe/osiptel/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "INDECOPI",
     "url": "https://www.indecopi.gob.pe/",
     "rss_url": "https://www.gob.pe/indecopi/noticias.rss", "tipo": "rss"},
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "Direccion de Casinos (Apuestas Deportivas)",
     "url": "https://www.gob.pe/mincetur",
     "tipo": "manual",
     "notas": "Resoluciones de la Direccion General de Juegos de Casino y Maquinas Tragamonedas"},

    # --- TEMAS AGRARIOS ---
    {"categoria": "Temas Agrarios", "pais": "PE",
     "nombre": "Ministerio del Desarrollo Agrario y Riego",
     "url": "https://www.gob.pe/midagri",
     "rss_url": "https://www.gob.pe/midagri/noticias.rss", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "PE",
     "nombre": "Ministerio de la Produccion",
     "url": "https://www.gob.pe/produce",
     "rss_url": "https://www.gob.pe/produce/noticias.rss", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "PE",
     "nombre": "Ministerio del Ambiente",
     "url": "https://www.gob.pe/minam",
     "rss_url": "https://www.gob.pe/minam/noticias.rss", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "PE", "nombre": "SENASA",
     "url": "https://www.gob.pe/senasa",
     "rss_url": "https://www.gob.pe/senasa/noticias.rss", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "PE",
     "nombre": "CAP (Convencion Agropecuaria)",
     "url": "https://convencionagropecuaria.com.pe/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "PE", "nombre": "CONVEAGRO",
     "url": "https://www.conveagro.org.pe/",
     "rss_url": "https://www.conveagro.org.pe/feed/", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "PE", "nombre": "Agraria.pe",
     "url": "https://agraria.pe/",
     "rss_url": "https://agraria.pe/rss", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "PE", "nombre": "AGAP",
     "url": "https://agapperu.org/", "tipo": "html",
     "notas": "Asociacion de Gremios Productores Agrarios del Peru"},
    {"categoria": "Temas Agrarios", "pais": "PE", "nombre": "CEPES",
     "url": "https://www.cepes.org.pe/",
     "rss_url": "https://www.cepes.org.pe/feed/", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "PE",
     "nombre": "Sociedad Peruana de Derecho Ambiental",
     "url": "https://spda.org.pe/",
     "rss_url": "https://spda.org.pe/feed/", "tipo": "rss"},

    # --- KYC / AML ---
    {"categoria": "Temas KYC/AML", "pais": "PE", "nombre": "SBS - Resoluciones",
     "url": "https://www.sbs.gob.pe/", "tipo": "html",
     "notas": "Superintendencia de Banca, Seguros y AFP - normativa"},

    # --- TEMAS SALUD ---
    {"categoria": "Temas Salud", "pais": "PE", "nombre": "Ministerio de Salud",
     "url": "https://www.gob.pe/minsa",
     "rss_url": "https://www.gob.pe/minsa/noticias.rss", "tipo": "rss"},
    {"categoria": "Temas Salud", "pais": "PE",
     "nombre": "Ministerio de Salud (estadisticas)",
     "url": "https://www.dge.gob.pe/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "PE", "nombre": "DIGEMID",
     "url": "https://www.gob.pe/digemid",
     "rss_url": "https://www.gob.pe/digemid/noticias.rss", "tipo": "rss"},
    {"categoria": "Temas Salud", "pais": "PE",
     "nombre": "Colegio de Quimicos Farmaceuticos del Peru",
     "url": "https://cqfp.pe/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "PE", "nombre": "Voces Ciudadanas",
     "url": "https://vocesciudadanas.org.pe/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "PE", "nombre": "Esperantra",
     "url": "https://esperantra.org/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "PE", "nombre": "Lazo Rosado",
     "url": "https://lazorosado.org/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "PE",
     "nombre": "Federacion Peruana de Enfermedades Raras",
     "url": "https://fepper.org.pe/", "tipo": "html"},

    # --- TEMAS TECH ---
    {"categoria": "Temas Tech", "pais": "PE", "nombre": "Niubox Legal",
     "url": "https://niubox.legal/",
     "rss_url": "https://niubox.legal/feed/", "tipo": "rss"},
    {"categoria": "Temas Tech", "pais": "PE", "nombre": "Comex Peru",
     "url": "https://www.comexperu.org.pe/",
     "rss_url": "https://www.comexperu.org.pe/feed/", "tipo": "rss"},
    {"categoria": "Temas Tech", "pais": "PE", "nombre": "DPL News Peru",
     "url": "https://dplnews.com/",
     "rss_url": "https://dplnews.com/feed/", "tipo": "rss",
     "notas": "Filtrar por etiqueta Peru en el feed"},
    {"categoria": "Temas Tech", "pais": "PE", "nombre": "Hiperderecho",
     "url": "https://hiperderecho.org/",
     "rss_url": "https://hiperderecho.org/feed/", "tipo": "rss"},
    {"categoria": "Temas Tech", "pais": "PE", "nombre": "Bloomberg en Linea",
     "url": "https://www.bloomberglinea.com/",
     "rss_url": "https://www.bloomberglinea.com/arc/outboundfeeds/rss/?outputType=xml",
     "tipo": "rss"},
    {"categoria": "Temas Tech", "pais": "PE",
     "nombre": "Asociacion Latinoamericana de Internet",
     "url": "https://alai.lat/",
     "rss_url": "https://alai.lat/feed/", "tipo": "rss"},
    {"categoria": "Temas Tech", "pais": "PE", "nombre": "Ebiz Latam",
     "url": "https://ebizlatam.com/",
     "rss_url": "https://ebizlatam.com/feed/", "tipo": "rss"},

    # --- INSTITUCIONES adicionales del catalogo del cliente ---
    {"categoria": "Institucion", "pais": "PE", "nombre": "PCM",
     "url": "https://www.gob.pe/institucion/pcm/noticias", "tipo": "html",
     "notas": "Presidencia del Consejo de Ministros"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "Presidencia",
     "url": "https://www.gob.pe/institucion/presidencia/noticias",
     "tipo": "html"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "MEF",
     "url": "https://www.gob.pe/institucion/mef/noticias", "tipo": "html",
     "notas": "Ministerio de Economia y Finanzas"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "MINEDU",
     "url": "https://www.gob.pe/institucion/minedu/noticias", "tipo": "html"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "MINCETUR",
     "url": "https://www.gob.pe/institucion/mincetur/noticias",
     "tipo": "html",
     "notas": "Incluye apuestas deportivas / casinos"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "MTC",
     "url": "https://www.gob.pe/institucion/mtc/noticias", "tipo": "html",
     "notas": "Transportes y Comunicaciones"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "MINAM",
     "url": "https://www.gob.pe/institucion/minam/noticias", "tipo": "html",
     "notas": "Ambiente — agro / cambio climatico"},
    {"categoria": "Institucion", "pais": "PE", "nombre": "PRODUCE",
     "url": "https://www.gob.pe/institucion/produce/noticias",
     "tipo": "html",
     "notas": "Produccion / pesca / industria"},

    # --- REGULATORIO: portales oficiales de normas ---
    # NOTA: estas fuentes publican normativa (no noticias). El scraper
    # generico intenta heuristica de titulo/link; cobertura puede ser
    # parcial. TODO: scraper especifico para PDFs del Peruano.
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "El Peruano - Normas Legales",
     "url": "https://diariooficial.elperuano.pe/Normas", "tipo": "html",
     "notas": "Decretos / resoluciones / leyes publicadas"},
    {"categoria": "Institucion", "pais": "PE",
     "nombre": "SBS - Resoluciones",
     "url": "https://www.sbs.gob.pe/normativa/normativa-sbs",
     "tipo": "html",
     "notas": "Normativa financiera SBS"},
]


# ============================================================
# ECUADOR
# ============================================================
FUENTES_EC: list[dict] = [
    # --- COYUNTURA POLITICA ---
    {"categoria": "Coyuntura Politica", "pais": "EC", "nombre": "El Comercio",
     "url": "https://www.elcomercio.com/actualidad/",
     "rss_url": "https://www.elcomercio.com/feed/", "tipo": "rss"},
    {"categoria": "Coyuntura Politica", "pais": "EC", "nombre": "El Universo",
     "url": "https://www.eluniverso.com/noticias/politica/",
     "rss_url": "https://www.eluniverso.com/rss/politica/", "tipo": "rss"},
    {"categoria": "Coyuntura Politica", "pais": "EC", "nombre": "PRIMICIAS",
     "url": "https://www.primicias.ec/politica/",
     "rss_url": "https://www.primicias.ec/rss/", "tipo": "rss"},
    {"categoria": "Coyuntura Politica", "pais": "EC", "nombre": "Gestion",
     "url": "https://www.revistagestion.ec/", "tipo": "html"},
    {"categoria": "Coyuntura Politica", "pais": "EC",
     "nombre": "Bloomberg Linea Ecuador",
     "url": "https://www.bloomberglinea.com/ecuador/",
     "rss_url": "https://www.bloomberglinea.com/arc/outboundfeeds/rss/?outputType=xml",
     "tipo": "rss"},

    # --- INSTITUCION ---
    {"categoria": "Institucion", "pais": "EC",
     "nombre": "Asamblea Nacional - Proyectos de Ley",
     "url": "https://proyectosdeley.asambleanacional.gob.ec/",
     "tipo": "html",
     "notas": "Cubierto por modulo scraper_ec/"},
    {"categoria": "Institucion", "pais": "EC", "nombre": "Registro Oficial",
     "url": "https://www.registroficial.gob.ec/", "tipo": "html"},
    {"categoria": "Institucion", "pais": "EC", "nombre": "Decretos Presidenciales",
     "url": "https://www.presidencia.gob.ec/decretos/", "tipo": "html"},
    {"categoria": "Institucion", "pais": "EC",
     "nombre": "Portal de la Asamblea Nacional",
     "url": "https://www.asambleanacional.gob.ec/",
     "rss_url": "https://www.asambleanacional.gob.ec/es/noticias/feed",
     "tipo": "rss"},
    {"categoria": "Institucion", "pais": "EC",
     "nombre": "Agenda de la Asamblea Nacional",
     "url": "https://www.asambleanacional.gob.ec/es/agenda_de_comunicacion",
     "tipo": "html",
     "notas": "Cubierto por modulo agenda_ec/"},
    {"categoria": "Institucion", "pais": "EC",
     "nombre": "Ministerio de Economia y Finanzas",
     "url": "https://www.finanzas.gob.ec/", "tipo": "html"},
    {"categoria": "Institucion", "pais": "EC",
     "nombre": "Ministerio de Relaciones Exteriores y Movilidad Humana",
     "url": "https://www.cancilleria.gob.ec/", "tipo": "html"},
    {"categoria": "Institucion", "pais": "EC",
     "nombre": "ARCSA (Regulacion Sanitaria)",
     "url": "https://www.controlsanitario.gob.ec/", "tipo": "html"},

    # --- TEMAS AGRARIOS ---
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Resoluciones Ministerio de Agricultura",
     "url": "https://www.agricultura.gob.ec/normativa/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Ministerio de Agricultura y Ganaderia",
     "url": "https://www.agricultura.gob.ec/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Ministerio del Ambiente",
     "url": "https://www.ambiente.gob.ec/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Ministerio de Produccion Comercio Exterior",
     "url": "https://www.produccion.gob.ec/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Agencia de Regulacion y Control Fito y Zoosanitario",
     "url": "https://www.agrocalidad.gob.ec/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC", "nombre": "Agrocalidad Noticias",
     "url": "https://www.agrocalidad.gob.ec/noticias/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "CONAIE (Confederacion Indigenas)",
     "url": "https://conaie.org/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC", "nombre": "El Productor",
     "url": "https://elproductor.com/",
     "rss_url": "https://elproductor.com/feed/", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Observatorio de Cambio Rural",
     "url": "https://ocaru.org.ec/",
     "rss_url": "https://ocaru.org.ec/feed/", "tipo": "rss"},
    {"categoria": "Temas Agrarios", "pais": "EC", "nombre": "INIAP",
     "url": "https://www.iniap.gob.ec/", "tipo": "html"},

    # --- KYC / AML ---
    {"categoria": "Temas KYC/AML", "pais": "EC",
     "nombre": "Ministerio de Telecomunicaciones",
     "url": "https://www.telecomunicaciones.gob.ec/", "tipo": "html"},
    {"categoria": "Temas KYC/AML", "pais": "EC",
     "nombre": "Superintendencia de Proteccion de Datos Personales",
     "url": "https://www.proteccionderechos.gob.ec/", "tipo": "html"},
    {"categoria": "Temas KYC/AML", "pais": "EC", "nombre": "DPL News Ecuador",
     "url": "https://dplnews.com/",
     "rss_url": "https://dplnews.com/feed/", "tipo": "rss"},

    # --- TEMAS SALUD ---
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "Proyectos normativos ARCSA",
     "url": "https://www.controlsanitario.gob.ec/proyectos-normativos/",
     "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC",
     "nombre": "Ministerio de Salud Publica",
     "url": "https://www.salud.gob.ec/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "IESS (Seg. Social)",
     "url": "https://www.iess.gob.ec/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "ALAFAR Ecuador",
     "url": "https://www.alafar.org/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "SOLCA Ecuador",
     "url": "https://www.solca.med.ec/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC",
     "nombre": "Jovenes Contra el Cancer Ecuador",
     "url": "https://jovenescontraelcancerec.org/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "Pacientes Ecuador",
     "url": "https://pacientesecuador.org/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "Edicion Medica",
     "url": "https://www.edicionmedica.ec/",
     "rss_url": "https://www.edicionmedica.ec/rss", "tipo": "rss"},

    # --- TEMAS TECH ---
    {"categoria": "Temas Tech", "pais": "EC", "nombre": "Criptonoticias",
     "url": "https://www.criptonoticias.com/",
     "rss_url": "https://www.criptonoticias.com/feed/", "tipo": "rss"},
    {"categoria": "Temas Tech", "pais": "EC",
     "nombre": "Camara Ecuatoriana de Comercio Exterior",
     "url": "https://www.cce.org.ec/", "tipo": "html"},
    {"categoria": "Temas Tech", "pais": "EC", "nombre": "Forbes Digital Ecuador",
     "url": "https://www.forbes.com.ec/",
     "rss_url": "https://www.forbes.com.ec/feed/", "tipo": "rss"},
    {"categoria": "Temas Tech", "pais": "EC", "nombre": "DPL Tech Ecuador",
     "url": "https://dplnews.com/", "tipo": "rss",
     "rss_url": "https://dplnews.com/feed/"},
    {"categoria": "Temas Tech", "pais": "EC",
     "nombre": "Camara de Innovacion y Tecnologia Ecuatoriana",
     "url": "https://www.cite.org.ec/", "tipo": "html"},
    {"categoria": "Temas Tech", "pais": "EC",
     "nombre": "Camara Ecuatoriana Comercio Exterior - Blog",
     "url": "https://cece.ec/blog/", "tipo": "html"},
    {"categoria": "Temas Tech", "pais": "EC",
     "nombre": "MinTel EC",
     "url": "https://www.telecomunicaciones.gob.ec/category/catactualidad/",
     "tipo": "html",
     "notas": "Telecomunicaciones y Sociedad de la Informacion"},
    {"categoria": "Temas Tech", "pais": "EC",
     "nombre": "SPDP - Proteccion de Datos EC",
     "url": "https://spdp.gob.ec/", "tipo": "html",
     "notas": "Superintendencia de Proteccion de Datos Personales"},

    # --- INSTITUCIONES (decretos, normas, ministerios) ---
    {"categoria": "Institucion", "pais": "EC",
     "nombre": "Decretos Presidenciales EC",
     "url": "https://minka.presidencia.gob.ec/portal/usuarios_externos.jsf",
     "tipo": "html",
     "notas": "Portal de decretos presidenciales (login publico)"},
    {"categoria": "Institucion", "pais": "EC", "nombre": "MEF Ecuador",
     "url": "https://www.finanzas.gob.ec/", "tipo": "html",
     "notas": "Ministerio de Economia y Finanzas"},
    {"categoria": "Institucion", "pais": "EC", "nombre": "Cancilleria EC",
     "url": "https://www.cancilleria.gob.ec/", "tipo": "html"},

    # --- TEMAS SALUD (adicionales) ---
    {"categoria": "Temas Salud", "pais": "EC",
     "nombre": "MSP - Ministerio de Salud Publica EC",
     "url": "https://www.salud.gob.ec/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "IESS",
     "url": "https://www.iess.gob.ec/", "tipo": "html"},
    {"categoria": "Temas Salud", "pais": "EC",
     "nombre": "ARCSA - Noticias",
     "url": "https://www.controlsanitario.gob.ec/noticias/", "tipo": "html",
     "notas": "Agencia Nacional de Regulacion Sanitaria"},
    {"categoria": "Temas Salud", "pais": "EC",
     "nombre": "ARCSA - Proyectos normativos en consulta",
     "url": "https://www.controlsanitario.gob.ec/matriz-de-proyectos-de-normativa-consulta-publica/",
     "tipo": "html",
     "notas": "Normativa en consulta publica (regulatorio salud/farma)"},
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "Pacientes Ecuador",
     "url": "https://pacientesecuador.org/noticias/", "tipo": "html",
     "notas": "Coalicion de organizaciones de pacientes"},
    {"categoria": "Temas Salud", "pais": "EC", "nombre": "Edicion Medica EC",
     "url": "https://www.edicionmedica.ec/", "tipo": "html"},

    # --- TEMAS AGRARIOS (adicionales del catalogo del cliente) ---
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Min Agricultura EC - Acuerdos Ministeriales",
     "url": "https://www.agricultura.gob.ec/acuerdos-ministeriales/",
     "tipo": "html",
     "notas": "Normativa agraria publicada por MAG"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Min Agricultura EC - Noticias",
     "url": "https://www.agricultura.gob.ec/noticias/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Min Ambiente EC",
     "url": "https://www.ambiente.gob.ec/noticias/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Min Produccion EC",
     "url": "https://www.produccion.gob.ec/noticias/", "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "AGROCALIDAD - Noticias",
     "url": "https://www.agrocalidad.gob.ec/category/noticias/",
     "tipo": "html"},
    {"categoria": "Temas Agrarios", "pais": "EC", "nombre": "INIAP",
     "url": "https://www.iniap.gob.ec/noticias/", "tipo": "html",
     "notas": "Instituto de Investigaciones Agropecuarias"},
    {"categoria": "Temas Agrarios", "pais": "EC",
     "nombre": "Observatorio del Cambio Rural",
     "url": "https://ocaru.org.ec/", "tipo": "html"},
]


def all_fuentes() -> list[dict]:
    return FUENTES_PE + FUENTES_EC
