[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#121212"
font = "sans serif"

[server]
headless = false
runOnSave = true

[browser]
gatherUsageStats = false
