[theme]
base = "light"
primaryColor = "#0A294D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#0A294D"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
